name: Build and Push Docker Image

on:
  push:
    branches:
      - "**"  # Triggers when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ "anilapato" }}
        password: ${{ "Password@123" }}

    - name: Build Docker image
      run: |
        docker build -t ${{ "anilapato" }}/maven-3.6.0-jdk8:latest .
      
    - name: Push Docker image
      run: |
        docker push ${{ "anilapato" }}/maven-3.6.0-jdk8:latest
